version: "3.8"

networks:
  dev-net:
    name: dev-net
    driver: bridge

volumes:
  elasticsearch-data:

services:
  elasticsearch:
    image: elasticsearch:8.6.0
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - dev-net
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.60
    container_name: kibana
    restart: unless-stopped
    networks:
      - dev-net
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
